backend:
  name: github
  repo: Fardibazz/freshyo

media_folder: static/img
public_folder: /img
site_url: https://freshyo.netlify.app/

collections:
  - name: components
    label: Components
    description: Komponen penyusun website
    files:
      - name: nav
        label: Site Navigation
        file: content/components/nav.json
        fields:
          - { name: logo, widget: image }
          - { name: name, widget: string }

          - name: menu
            label: Menu
            widget: list
            fields:
              - { name: to, widget: string }
              - { name: label, widget: string }

      - name: banners
        label: Banners
        file: content/components/banners.json
        fields:
          - name: homeBanner
            label: Home Banners
            label_singular: Home Banner
            widget: list
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: img, widget: image }

          - name: orderBanner
            label: Order Banner
            widget: object
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: img, widget: image }

          - name: aboutBanner
            label: About Banners
            label_singular: About Banner
            widget: list
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: img, widget: image }

          - name: contactBanner
            label: Contact Banner
            widget: object
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: img, widget: image }

      - name: footer
        label: Site Footer
        file: content/components/footer.json
        widget: "object"
        fields:
          - { name: locationLabel, label: Location Label, widget: string }
          - name: places
            label: Places
            label_singular: Place
            widget: list
            fields:
              - { name: address, widget: string }
              - { name: city, widget: string }

          - { name: hoursLabel, label: Hours Label, widget: string }
          - name: hours
            label: Time
            widget: list
            fields:
              - { name: days, widget: string }

          - { name: text, widget: string }

      - name: socialMedia
        label: Social Media
        file: content/components/social-media.json
        fields:
          - name: accounts
            label_singular: account
            widget: listtittitlele
            fields:
              - { name: icon, widget: string }
              - { name: link, widget: string }
    format: json

  - name: pages
    label: Pages
    description: Halaman penyusun website
    files:
      - name: home
        label: Home Page
        file: content/pages/home.json
        fields:
          - name: header
            fields:
              - { name: cursive, widget: string }
              - { name: title, widget: string }
              - { name: subtitle, widget: string }
              - { name: img, widget: image }

          - name: homeAbout
            label: Home - About
            widget: object
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: content, widget: markdown }
              - { name: link, widget: string }
              - { name: to, widget: string }
              - { name: img, widget: image }

          - name: homeProducts
            label: Home - Products
            widget: object
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: content, widget: markdown }
              - { name: link, widget: string }
              - { name: to, widget: string }
              - name: productsShowcase
                label: Images
                label_singular: Image
                widget: list
                fields:
                  - { name: img, widget: image }

          - name: homeOrder
            label: Home - Order
            widget: object
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: content, widget: markdown }
              - { name: link, widget: string }
              - { name: to, widget: string }
              - name: orderShowcase
                label: Images
                label_singular: Image
                widget: list
                fields:
                  - { name: img, widget: image }

          - name: homeTestimonies
            label: Home - Testimonies
            widget: object
            fields:
              - { name: cursive, widget: string }
              - { name: text, widget: string }
              - { name: content, widget: markdown }
              - name: testimoniesShowcase
                label: Testimonies
                label_singular: Testimony
                widget: list
                fields:
                  - { name: title, widget: string }
                  - { name: text, widget: string }
                  - { name: img, widget: image }

      - name: order
        label: Order Page
        file: content/pages/order.json
        fields:
          - name: titles
            label: Titles
            label_singular: Titles
            widget: list
            fields:
              - { name: type, widget: select, options: ["yoghurt"] }
              - { name: label, widget: string }

          - name: products
            label: Products
            label_singular: Product
            widget: list
            fields:
              - { name: name, widget: string }
              - { name: price, widget: number }
              - { name: description, widget: string }
              - { name: img, widget: image }
              - { name: type, widget: select, options: ["yoghurt"] }

      - name: about
        label: About Page
        file: content/pages/about.json
        fields:
          - name: history
            widget: object
            fields:
              - { name: title, widget: string }
              - { name: content, widget: string }

          - name: quote
            widget: object
            fields:
              - { name: content, widget: string }
              - { name: img, widget: image }
              - { name: name, widget: string }

          - name: today
            widget: object
            fields:
              - { name: title, widget: string }
              - { name: content, widget: string }

      - name: contact
        label: Contact Page
        file: content/pages/contact.json
        fields:
          - name: form
            widget: object
            fields:
              - { name: intro, widget: string }
              - { name: email, widget: string }
              - {
                  name: namePlaceholder,
                  label: Name Placeholder,
                  widget: string
                }
              - {
                  name: emailPlaceholder,
                  label: Email Placeholder,
                  widget: string
                }
              - {
                  name: messagePlaceholder,
                  label: Message Placeholder,
                  widget: string
                }
              - { name: map, widget: markdown }

              - name: phone
                label: Phone Numbers
                label_singular: Phone Number
                widget: list
                fields:
                  - { name: number, widget: string }
    format: json
